<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>KeygenApp</RootNamespace>
    <AssemblyName>KeygenApp</AssemblyName>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <Platforms>x64;x86;AnyCPU</Platforms>
  </PropertyGroup>

</Project>
